/* Generated by Yosys 0.33 (git sha1 2584903a060, clang++ 11.1.0 -fPIC -Os) */

module cfloat8_mul(CLK, RST_N, send_data_input, EN_send, RDY_send, receive, RDY_receive);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  input CLK;
  wire CLK;
  input EN_send;
  wire EN_send;
  output RDY_receive;
  wire RDY_receive;
  output RDY_send;
  wire RDY_send;
  input RST_N;
  wire RST_N;
  wire \buffer1_bias$D_IN[0] ;
  wire \buffer1_bias$D_IN[1] ;
  wire \buffer1_bias$D_IN[2] ;
  wire \buffer1_bias$D_IN[3] ;
  wire \buffer1_bias[0] ;
  wire \buffer1_bias[1] ;
  wire \buffer1_bias[2] ;
  wire \buffer1_bias[3] ;
  wire \buffer1_exp1$D_IN[0] ;
  wire \buffer1_exp1$D_IN[1] ;
  wire \buffer1_exp1$D_IN[2] ;
  wire \buffer1_exp1$D_IN[3] ;
  wire \buffer1_exp1[0] ;
  wire \buffer1_exp1[1] ;
  wire \buffer1_exp1[2] ;
  wire \buffer1_exp1[3] ;
  wire \buffer1_exp2$D_IN[0] ;
  wire \buffer1_exp2$D_IN[1] ;
  wire \buffer1_exp2$D_IN[2] ;
  wire \buffer1_exp2$D_IN[3] ;
  wire \buffer1_exp2[0] ;
  wire \buffer1_exp2[1] ;
  wire \buffer1_exp2[2] ;
  wire \buffer1_exp2[3] ;
  wire \buffer1_man1$D_IN[0] ;
  wire \buffer1_man1$D_IN[1] ;
  wire \buffer1_man1$D_IN[2] ;
  wire \buffer1_man1[0] ;
  wire \buffer1_man1[1] ;
  wire \buffer1_man1[2] ;
  wire \buffer1_man2$D_IN[0] ;
  wire \buffer1_man2$D_IN[1] ;
  wire \buffer1_man2$D_IN[2] ;
  wire \buffer1_man2[0] ;
  wire \buffer1_man2[1] ;
  wire \buffer1_man2[2] ;
  wire buffer1_rmode;
  wire \buffer1_rmode$D_IN ;
  wire buffer1_sign1;
  wire \buffer1_sign1$D_IN ;
  wire buffer1_sign2;
  wire \buffer1_sign2$D_IN ;
  wire \buffer2_bias[0] ;
  wire \buffer2_bias[1] ;
  wire \buffer2_bias[2] ;
  wire \buffer2_bias[3] ;
  wire \buffer2_exp1[0] ;
  wire \buffer2_exp1[1] ;
  wire \buffer2_exp1[2] ;
  wire \buffer2_exp1[3] ;
  wire \buffer2_exp2[0] ;
  wire \buffer2_exp2[1] ;
  wire \buffer2_exp2[2] ;
  wire \buffer2_exp2[3] ;
  wire \buffer2_man1[0] ;
  wire \buffer2_man1[1] ;
  wire \buffer2_man1[2] ;
  wire \buffer2_man2[0] ;
  wire \buffer2_man2[1] ;
  wire \buffer2_man2[2] ;
  wire buffer2_rmode;
  wire \buffer3_exp$D_IN[0] ;
  wire \buffer3_exp$D_IN[1] ;
  wire \buffer3_exp$D_IN[2] ;
  wire \buffer3_exp$D_IN[3] ;
  wire \buffer3_exp1[0] ;
  wire \buffer3_exp1[1] ;
  wire \buffer3_exp1[2] ;
  wire \buffer3_exp1[3] ;
  wire \buffer3_exp2[0] ;
  wire \buffer3_exp2[1] ;
  wire \buffer3_exp2[2] ;
  wire \buffer3_exp2[3] ;
  wire \buffer3_exp[0] ;
  wire \buffer3_exp[1] ;
  wire \buffer3_exp[2] ;
  wire \buffer3_exp[3] ;
  wire \buffer3_man1[0] ;
  wire \buffer3_man1[1] ;
  wire \buffer3_man1[2] ;
  wire \buffer3_man2[0] ;
  wire \buffer3_man2[1] ;
  wire \buffer3_man2[2] ;
  wire buffer3_rmode;
  wire \buffer4_exp[0] ;
  wire \buffer4_exp[1] ;
  wire \buffer4_exp[2] ;
  wire \buffer4_exp[3] ;
  wire buffer4_rmode;
  wire buffer5_rmode;
  wire \final_man[0] ;
  wire \final_man[1] ;
  wire \final_man[2] ;
  wire \final_man[3] ;
  wire \final_man[4] ;
  wire \final_man[5] ;
  wire \final_man[6] ;
  wire \final_man[7] ;
  wire final_sign;
  wire \normalized_exp[0] ;
  wire \normalized_exp[1] ;
  wire \normalized_exp[2] ;
  wire \normalized_exp[3] ;
  wire \normalized_man[2] ;
  wire \normalized_man[3] ;
  wire \normalized_man[4] ;
  wire \normalized_man[5] ;
  output [7:0] receive;
  wire [7:0] receive;
  wire \rounded_man[0] ;
  wire \rounded_man[1] ;
  wire \rounded_man[2] ;
  input [20:0] send_data_input;
  wire [20:0] send_data_input;
  wire \stage1_output[7] ;
  wire \stage2_output[7] ;
  wire \stage3_output[7] ;
  wire \stage4_output[3] ;
  wire \stage4_output[4] ;
  wire \stage4_output[5] ;
  wire \stage4_output[6] ;
  wire \stage4_output[7] ;
  sky130_fd_sc_hd__and4_2 _432_ (
    .A(\buffer4_exp[0] ),
    .B(\buffer4_exp[1] ),
    .C(\buffer4_exp[2] ),
    .D(\buffer4_exp[3] ),
    .X(_126_)
  );
  sky130_fd_sc_hd__buf_1 _433_ (
    .A(_126_),
    .X(_127_)
  );
  sky130_fd_sc_hd__o21a_2 _434_ (
    .A1(\rounded_man[0] ),
    .A2(_127_),
    .B1(RST_N),
    .X(_000_)
  );
  sky130_fd_sc_hd__o21a_2 _435_ (
    .A1(\rounded_man[1] ),
    .A2(_127_),
    .B1(RST_N),
    .X(_001_)
  );
  sky130_fd_sc_hd__o21a_2 _436_ (
    .A1(\rounded_man[2] ),
    .A2(_127_),
    .B1(RST_N),
    .X(_002_)
  );
  sky130_fd_sc_hd__o21a_2 _437_ (
    .A1(\stage4_output[3] ),
    .A2(_127_),
    .B1(RST_N),
    .X(_003_)
  );
  sky130_fd_sc_hd__o21a_2 _438_ (
    .A1(\stage4_output[4] ),
    .A2(_127_),
    .B1(RST_N),
    .X(_004_)
  );
  sky130_fd_sc_hd__o21a_2 _439_ (
    .A1(\stage4_output[5] ),
    .A2(_127_),
    .B1(RST_N),
    .X(_005_)
  );
  sky130_fd_sc_hd__o21a_2 _440_ (
    .A1(\stage4_output[6] ),
    .A2(_126_),
    .B1(RST_N),
    .X(_006_)
  );
  sky130_fd_sc_hd__and2_2 _441_ (
    .A(RST_N),
    .B(\stage4_output[7] ),
    .X(_128_)
  );
  sky130_fd_sc_hd__buf_1 _442_ (
    .A(_128_),
    .X(_007_)
  );
  sky130_fd_sc_hd__or2b_2 _443_ (
    .A(\final_man[7] ),
    .B_N(\final_man[6] ),
    .X(_129_)
  );
  sky130_fd_sc_hd__buf_1 _444_ (
    .A(_129_),
    .X(_130_)
  );
  sky130_fd_sc_hd__and2b_2 _445_ (
    .A_N(\final_man[7] ),
    .B(\final_man[6] ),
    .X(_131_)
  );
  sky130_fd_sc_hd__buf_1 _446_ (
    .A(_131_),
    .X(_132_)
  );
  sky130_fd_sc_hd__or2_2 _447_ (
    .A(\normalized_exp[0] ),
    .B(_132_),
    .X(_133_)
  );
  sky130_fd_sc_hd__o211a_2 _448_ (
    .A1(\buffer3_exp[0] ),
    .A2(_130_),
    .B1(_133_),
    .C1(RST_N),
    .X(_008_)
  );
  sky130_fd_sc_hd__or2_2 _449_ (
    .A(\normalized_exp[1] ),
    .B(_132_),
    .X(_134_)
  );
  sky130_fd_sc_hd__o211a_2 _450_ (
    .A1(\buffer3_exp[1] ),
    .A2(_130_),
    .B1(_134_),
    .C1(RST_N),
    .X(_009_)
  );
  sky130_fd_sc_hd__or2_2 _451_ (
    .A(\normalized_exp[2] ),
    .B(_132_),
    .X(_135_)
  );
  sky130_fd_sc_hd__o211a_2 _452_ (
    .A1(\buffer3_exp[2] ),
    .A2(_130_),
    .B1(_135_),
    .C1(RST_N),
    .X(_010_)
  );
  sky130_fd_sc_hd__or2_2 _453_ (
    .A(\normalized_exp[3] ),
    .B(_132_),
    .X(_136_)
  );
  sky130_fd_sc_hd__o211a_2 _454_ (
    .A1(\buffer3_exp[3] ),
    .A2(_130_),
    .B1(_136_),
    .C1(RST_N),
    .X(_011_)
  );
  sky130_fd_sc_hd__and2_2 _455_ (
    .A(RST_N),
    .B(\stage3_output[7] ),
    .X(_137_)
  );
  sky130_fd_sc_hd__buf_1 _456_ (
    .A(_137_),
    .X(_012_)
  );
  sky130_fd_sc_hd__and2_2 _457_ (
    .A(RST_N),
    .B(\buffer3_exp$D_IN[3] ),
    .X(_138_)
  );
  sky130_fd_sc_hd__buf_1 _458_ (
    .A(_138_),
    .X(_013_)
  );
  sky130_fd_sc_hd__and2_2 _459_ (
    .A(RST_N),
    .B(\stage2_output[7] ),
    .X(_139_)
  );
  sky130_fd_sc_hd__buf_1 _460_ (
    .A(_139_),
    .X(_014_)
  );
  sky130_fd_sc_hd__and2_2 _461_ (
    .A(\buffer1_bias$D_IN[0] ),
    .B(RST_N),
    .X(_140_)
  );
  sky130_fd_sc_hd__buf_1 _462_ (
    .A(_140_),
    .X(_015_)
  );
  sky130_fd_sc_hd__and2_2 _463_ (
    .A(\buffer1_bias$D_IN[1] ),
    .B(RST_N),
    .X(_141_)
  );
  sky130_fd_sc_hd__buf_1 _464_ (
    .A(_141_),
    .X(_016_)
  );
  sky130_fd_sc_hd__and2_2 _465_ (
    .A(\buffer1_bias$D_IN[2] ),
    .B(RST_N),
    .X(_142_)
  );
  sky130_fd_sc_hd__buf_1 _466_ (
    .A(_142_),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_2 _467_ (
    .A(\buffer1_bias$D_IN[3] ),
    .B(RST_N),
    .X(_143_)
  );
  sky130_fd_sc_hd__buf_1 _468_ (
    .A(_143_),
    .X(_018_)
  );
  sky130_fd_sc_hd__and2_2 _469_ (
    .A(\buffer1_exp1$D_IN[0] ),
    .B(RST_N),
    .X(_144_)
  );
  sky130_fd_sc_hd__buf_1 _470_ (
    .A(_144_),
    .X(_019_)
  );
  sky130_fd_sc_hd__and2_2 _471_ (
    .A(\buffer1_exp1$D_IN[1] ),
    .B(RST_N),
    .X(_145_)
  );
  sky130_fd_sc_hd__buf_1 _472_ (
    .A(_145_),
    .X(_020_)
  );
  sky130_fd_sc_hd__and2_2 _473_ (
    .A(\buffer1_exp1$D_IN[2] ),
    .B(RST_N),
    .X(_146_)
  );
  sky130_fd_sc_hd__buf_1 _474_ (
    .A(_146_),
    .X(_021_)
  );
  sky130_fd_sc_hd__and2_2 _475_ (
    .A(\buffer1_exp1$D_IN[3] ),
    .B(RST_N),
    .X(_147_)
  );
  sky130_fd_sc_hd__buf_1 _476_ (
    .A(_147_),
    .X(_022_)
  );
  sky130_fd_sc_hd__and2_2 _477_ (
    .A(\buffer1_exp2$D_IN[0] ),
    .B(RST_N),
    .X(_148_)
  );
  sky130_fd_sc_hd__buf_1 _478_ (
    .A(_148_),
    .X(_023_)
  );
  sky130_fd_sc_hd__and2_2 _479_ (
    .A(\buffer1_exp2$D_IN[1] ),
    .B(RST_N),
    .X(_149_)
  );
  sky130_fd_sc_hd__buf_1 _480_ (
    .A(_149_),
    .X(_024_)
  );
  sky130_fd_sc_hd__and2_2 _481_ (
    .A(\buffer1_exp2$D_IN[2] ),
    .B(RST_N),
    .X(_150_)
  );
  sky130_fd_sc_hd__buf_1 _482_ (
    .A(_150_),
    .X(_025_)
  );
  sky130_fd_sc_hd__and2_2 _483_ (
    .A(\buffer1_exp2$D_IN[3] ),
    .B(RST_N),
    .X(_151_)
  );
  sky130_fd_sc_hd__buf_1 _484_ (
    .A(_151_),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2_2 _485_ (
    .A(\buffer1_man1$D_IN[0] ),
    .B(RST_N),
    .X(_152_)
  );
  sky130_fd_sc_hd__buf_1 _486_ (
    .A(_152_),
    .X(_027_)
  );
  sky130_fd_sc_hd__and2_2 _487_ (
    .A(\buffer1_man1$D_IN[1] ),
    .B(RST_N),
    .X(_153_)
  );
  sky130_fd_sc_hd__buf_1 _488_ (
    .A(_153_),
    .X(_028_)
  );
  sky130_fd_sc_hd__and2_2 _489_ (
    .A(\buffer1_man1$D_IN[2] ),
    .B(RST_N),
    .X(_154_)
  );
  sky130_fd_sc_hd__buf_1 _490_ (
    .A(_154_),
    .X(_029_)
  );
  sky130_fd_sc_hd__and2_2 _491_ (
    .A(\buffer1_man2$D_IN[0] ),
    .B(RST_N),
    .X(_155_)
  );
  sky130_fd_sc_hd__buf_1 _492_ (
    .A(_155_),
    .X(_030_)
  );
  sky130_fd_sc_hd__and2_2 _493_ (
    .A(\buffer1_man2$D_IN[1] ),
    .B(RST_N),
    .X(_156_)
  );
  sky130_fd_sc_hd__buf_1 _494_ (
    .A(_156_),
    .X(_031_)
  );
  sky130_fd_sc_hd__and2_2 _495_ (
    .A(\buffer1_man2$D_IN[2] ),
    .B(RST_N),
    .X(_157_)
  );
  sky130_fd_sc_hd__buf_1 _496_ (
    .A(_157_),
    .X(_032_)
  );
  sky130_fd_sc_hd__and2_2 _497_ (
    .A(\buffer1_rmode$D_IN ),
    .B(RST_N),
    .X(_158_)
  );
  sky130_fd_sc_hd__buf_1 _498_ (
    .A(_158_),
    .X(_033_)
  );
  sky130_fd_sc_hd__and2_2 _499_ (
    .A(\buffer1_sign1$D_IN ),
    .B(RST_N),
    .X(_159_)
  );
  sky130_fd_sc_hd__buf_1 _500_ (
    .A(_159_),
    .X(_034_)
  );
  sky130_fd_sc_hd__and2_2 _501_ (
    .A(\buffer1_sign2$D_IN ),
    .B(RST_N),
    .X(_160_)
  );
  sky130_fd_sc_hd__buf_1 _502_ (
    .A(_160_),
    .X(_035_)
  );
  sky130_fd_sc_hd__and2_2 _503_ (
    .A(RST_N),
    .B(\buffer1_bias[0] ),
    .X(_161_)
  );
  sky130_fd_sc_hd__buf_1 _504_ (
    .A(_161_),
    .X(_036_)
  );
  sky130_fd_sc_hd__and2_2 _505_ (
    .A(RST_N),
    .B(\buffer1_bias[1] ),
    .X(_162_)
  );
  sky130_fd_sc_hd__buf_1 _506_ (
    .A(_162_),
    .X(_037_)
  );
  sky130_fd_sc_hd__and2_2 _507_ (
    .A(RST_N),
    .B(\buffer1_bias[2] ),
    .X(_163_)
  );
  sky130_fd_sc_hd__buf_1 _508_ (
    .A(_163_),
    .X(_038_)
  );
  sky130_fd_sc_hd__and2_2 _509_ (
    .A(RST_N),
    .B(\buffer1_bias[3] ),
    .X(_164_)
  );
  sky130_fd_sc_hd__buf_1 _510_ (
    .A(_164_),
    .X(_039_)
  );
  sky130_fd_sc_hd__and2_2 _511_ (
    .A(RST_N),
    .B(\buffer1_exp1[0] ),
    .X(_165_)
  );
  sky130_fd_sc_hd__buf_1 _512_ (
    .A(_165_),
    .X(_040_)
  );
  sky130_fd_sc_hd__and2_2 _513_ (
    .A(RST_N),
    .B(\buffer1_exp1[1] ),
    .X(_166_)
  );
  sky130_fd_sc_hd__buf_1 _514_ (
    .A(_166_),
    .X(_041_)
  );
  sky130_fd_sc_hd__and2_2 _515_ (
    .A(RST_N),
    .B(\buffer1_exp1[2] ),
    .X(_167_)
  );
  sky130_fd_sc_hd__buf_1 _516_ (
    .A(_167_),
    .X(_042_)
  );
  sky130_fd_sc_hd__and2_2 _517_ (
    .A(RST_N),
    .B(\buffer1_exp1[3] ),
    .X(_168_)
  );
  sky130_fd_sc_hd__buf_1 _518_ (
    .A(_168_),
    .X(_043_)
  );
  sky130_fd_sc_hd__and2_2 _519_ (
    .A(RST_N),
    .B(\buffer1_exp2[0] ),
    .X(_169_)
  );
  sky130_fd_sc_hd__buf_1 _520_ (
    .A(_169_),
    .X(_044_)
  );
  sky130_fd_sc_hd__and2_2 _521_ (
    .A(RST_N),
    .B(\buffer1_exp2[1] ),
    .X(_170_)
  );
  sky130_fd_sc_hd__buf_1 _522_ (
    .A(_170_),
    .X(_045_)
  );
  sky130_fd_sc_hd__and2_2 _523_ (
    .A(RST_N),
    .B(\buffer1_exp2[2] ),
    .X(_171_)
  );
  sky130_fd_sc_hd__buf_1 _524_ (
    .A(_171_),
    .X(_046_)
  );
  sky130_fd_sc_hd__and2_2 _525_ (
    .A(RST_N),
    .B(\buffer1_exp2[3] ),
    .X(_172_)
  );
  sky130_fd_sc_hd__buf_1 _526_ (
    .A(_172_),
    .X(_047_)
  );
  sky130_fd_sc_hd__and2_2 _527_ (
    .A(RST_N),
    .B(\buffer1_man1[0] ),
    .X(_173_)
  );
  sky130_fd_sc_hd__buf_1 _528_ (
    .A(_173_),
    .X(_048_)
  );
  sky130_fd_sc_hd__and2_2 _529_ (
    .A(RST_N),
    .B(\buffer1_man1[1] ),
    .X(_174_)
  );
  sky130_fd_sc_hd__buf_1 _530_ (
    .A(_174_),
    .X(_049_)
  );
  sky130_fd_sc_hd__and2_2 _531_ (
    .A(RST_N),
    .B(\buffer1_man1[2] ),
    .X(_175_)
  );
  sky130_fd_sc_hd__buf_1 _532_ (
    .A(_175_),
    .X(_050_)
  );
  sky130_fd_sc_hd__and2_2 _533_ (
    .A(RST_N),
    .B(\buffer1_man2[0] ),
    .X(_176_)
  );
  sky130_fd_sc_hd__buf_1 _534_ (
    .A(_176_),
    .X(_051_)
  );
  sky130_fd_sc_hd__and2_2 _535_ (
    .A(RST_N),
    .B(\buffer1_man2[1] ),
    .X(_177_)
  );
  sky130_fd_sc_hd__buf_1 _536_ (
    .A(_177_),
    .X(_052_)
  );
  sky130_fd_sc_hd__and2_2 _537_ (
    .A(RST_N),
    .B(\buffer1_man2[2] ),
    .X(_178_)
  );
  sky130_fd_sc_hd__buf_1 _538_ (
    .A(_178_),
    .X(_053_)
  );
  sky130_fd_sc_hd__and2_2 _539_ (
    .A(RST_N),
    .B(buffer1_rmode),
    .X(_179_)
  );
  sky130_fd_sc_hd__buf_1 _540_ (
    .A(_179_),
    .X(_054_)
  );
  sky130_fd_sc_hd__and2_2 _541_ (
    .A(RST_N),
    .B(\buffer3_exp$D_IN[0] ),
    .X(_180_)
  );
  sky130_fd_sc_hd__buf_1 _542_ (
    .A(_180_),
    .X(_055_)
  );
  sky130_fd_sc_hd__and2_2 _543_ (
    .A(RST_N),
    .B(\buffer3_exp$D_IN[1] ),
    .X(_181_)
  );
  sky130_fd_sc_hd__buf_1 _544_ (
    .A(_181_),
    .X(_056_)
  );
  sky130_fd_sc_hd__and2_2 _545_ (
    .A(RST_N),
    .B(\buffer3_exp$D_IN[2] ),
    .X(_182_)
  );
  sky130_fd_sc_hd__buf_1 _546_ (
    .A(_182_),
    .X(_057_)
  );
  sky130_fd_sc_hd__and2_2 _547_ (
    .A(\buffer2_exp1[0] ),
    .B(RST_N),
    .X(_183_)
  );
  sky130_fd_sc_hd__buf_1 _548_ (
    .A(_183_),
    .X(_058_)
  );
  sky130_fd_sc_hd__and2_2 _549_ (
    .A(\buffer2_exp1[1] ),
    .B(RST_N),
    .X(_184_)
  );
  sky130_fd_sc_hd__buf_1 _550_ (
    .A(_184_),
    .X(_059_)
  );
  sky130_fd_sc_hd__and2_2 _551_ (
    .A(\buffer2_exp1[2] ),
    .B(RST_N),
    .X(_185_)
  );
  sky130_fd_sc_hd__buf_1 _552_ (
    .A(_185_),
    .X(_060_)
  );
  sky130_fd_sc_hd__and2_2 _553_ (
    .A(\buffer2_exp1[3] ),
    .B(RST_N),
    .X(_186_)
  );
  sky130_fd_sc_hd__buf_1 _554_ (
    .A(_186_),
    .X(_061_)
  );
  sky130_fd_sc_hd__and2_2 _555_ (
    .A(\buffer2_exp2[0] ),
    .B(RST_N),
    .X(_187_)
  );
  sky130_fd_sc_hd__buf_1 _556_ (
    .A(_187_),
    .X(_062_)
  );
  sky130_fd_sc_hd__and2_2 _557_ (
    .A(\buffer2_exp2[1] ),
    .B(RST_N),
    .X(_188_)
  );
  sky130_fd_sc_hd__buf_1 _558_ (
    .A(_188_),
    .X(_063_)
  );
  sky130_fd_sc_hd__and2_2 _559_ (
    .A(\buffer2_exp2[2] ),
    .B(RST_N),
    .X(_189_)
  );
  sky130_fd_sc_hd__buf_1 _560_ (
    .A(_189_),
    .X(_064_)
  );
  sky130_fd_sc_hd__and2_2 _561_ (
    .A(\buffer2_exp2[3] ),
    .B(RST_N),
    .X(_190_)
  );
  sky130_fd_sc_hd__buf_1 _562_ (
    .A(_190_),
    .X(_065_)
  );
  sky130_fd_sc_hd__and2_2 _563_ (
    .A(RST_N),
    .B(\buffer2_man1[0] ),
    .X(_191_)
  );
  sky130_fd_sc_hd__buf_1 _564_ (
    .A(_191_),
    .X(_066_)
  );
  sky130_fd_sc_hd__and2_2 _565_ (
    .A(RST_N),
    .B(\buffer2_man1[1] ),
    .X(_192_)
  );
  sky130_fd_sc_hd__buf_1 _566_ (
    .A(_192_),
    .X(_067_)
  );
  sky130_fd_sc_hd__and2_2 _567_ (
    .A(RST_N),
    .B(\buffer2_man1[2] ),
    .X(_193_)
  );
  sky130_fd_sc_hd__buf_1 _568_ (
    .A(_193_),
    .X(_068_)
  );
  sky130_fd_sc_hd__and2_2 _569_ (
    .A(RST_N),
    .B(\buffer2_man2[0] ),
    .X(_194_)
  );
  sky130_fd_sc_hd__buf_1 _570_ (
    .A(_194_),
    .X(_069_)
  );
  sky130_fd_sc_hd__and2_2 _571_ (
    .A(RST_N),
    .B(\buffer2_man2[1] ),
    .X(_195_)
  );
  sky130_fd_sc_hd__buf_1 _572_ (
    .A(_195_),
    .X(_070_)
  );
  sky130_fd_sc_hd__and2_2 _573_ (
    .A(RST_N),
    .B(\buffer2_man2[2] ),
    .X(_196_)
  );
  sky130_fd_sc_hd__buf_1 _574_ (
    .A(_196_),
    .X(_071_)
  );
  sky130_fd_sc_hd__and2_2 _575_ (
    .A(RST_N),
    .B(buffer2_rmode),
    .X(_197_)
  );
  sky130_fd_sc_hd__buf_1 _576_ (
    .A(_197_),
    .X(_072_)
  );
  sky130_fd_sc_hd__and2_2 _577_ (
    .A(\buffer3_exp[0] ),
    .B(RST_N),
    .X(_198_)
  );
  sky130_fd_sc_hd__buf_1 _578_ (
    .A(_198_),
    .X(_073_)
  );
  sky130_fd_sc_hd__inv_2 _579_ (
    .A(\buffer3_exp[1] ),
    .Y(_199_)
  );
  sky130_fd_sc_hd__inv_2 _580_ (
    .A(RST_N),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nor2_2 _581_ (
    .A(_199_),
    .B(_200_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__and2_2 _582_ (
    .A(\buffer3_exp[2] ),
    .B(RST_N),
    .X(_201_)
  );
  sky130_fd_sc_hd__buf_1 _583_ (
    .A(_201_),
    .X(_075_)
  );
  sky130_fd_sc_hd__and2_2 _584_ (
    .A(\buffer3_exp[3] ),
    .B(RST_N),
    .X(_202_)
  );
  sky130_fd_sc_hd__buf_1 _585_ (
    .A(_202_),
    .X(_076_)
  );
  sky130_fd_sc_hd__and2_2 _586_ (
    .A(RST_N),
    .B(buffer3_rmode),
    .X(_203_)
  );
  sky130_fd_sc_hd__buf_1 _587_ (
    .A(_203_),
    .X(_077_)
  );
  sky130_fd_sc_hd__and2_2 _588_ (
    .A(RST_N),
    .B(buffer4_rmode),
    .X(_204_)
  );
  sky130_fd_sc_hd__buf_1 _589_ (
    .A(_204_),
    .X(_078_)
  );
  sky130_fd_sc_hd__and3_2 _590_ (
    .A(\buffer3_man2[0] ),
    .B(\buffer3_man1[0] ),
    .C(RST_N),
    .X(_205_)
  );
  sky130_fd_sc_hd__buf_1 _591_ (
    .A(_205_),
    .X(_079_)
  );
  sky130_fd_sc_hd__and4_2 _592_ (
    .A(\buffer3_man2[0] ),
    .B(\buffer3_man1[0] ),
    .C(\buffer3_man2[1] ),
    .D(\buffer3_man1[1] ),
    .X(_206_)
  );
  sky130_fd_sc_hd__a22o_2 _593_ (
    .A1(\buffer3_man1[0] ),
    .A2(\buffer3_man2[1] ),
    .B1(\buffer3_man1[1] ),
    .B2(\buffer3_man2[0] ),
    .X(_207_)
  );
  sky130_fd_sc_hd__and3b_2 _594_ (
    .A_N(_206_),
    .B(RST_N),
    .C(_207_),
    .X(_208_)
  );
  sky130_fd_sc_hd__buf_1 _595_ (
    .A(_208_),
    .X(_080_)
  );
  sky130_fd_sc_hd__a22o_2 _596_ (
    .A1(\buffer3_man2[1] ),
    .A2(\buffer3_man1[1] ),
    .B1(\buffer3_man2[2] ),
    .B2(\buffer3_man1[0] ),
    .X(_209_)
  );
  sky130_fd_sc_hd__and4_2 _597_ (
    .A(\buffer3_man1[0] ),
    .B(\buffer3_man2[1] ),
    .C(\buffer3_man1[1] ),
    .D(\buffer3_man2[2] ),
    .X(_210_)
  );
  sky130_fd_sc_hd__inv_2 _598_ (
    .A(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand4_2 _599_ (
    .A(\buffer3_man2[0] ),
    .B(\buffer3_man1[2] ),
    .C(_209_),
    .D(_211_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__a22o_2 _600_ (
    .A1(\buffer3_man2[0] ),
    .A2(\buffer3_man1[2] ),
    .B1(_209_),
    .B2(_211_),
    .X(_213_)
  );
  sky130_fd_sc_hd__and2_2 _601_ (
    .A(_212_),
    .B(_213_),
    .X(_214_)
  );
  sky130_fd_sc_hd__or2_2 _602_ (
    .A(_206_),
    .B(_214_),
    .X(_215_)
  );
  sky130_fd_sc_hd__nand2_2 _603_ (
    .A(_206_),
    .B(_214_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__and3_2 _604_ (
    .A(RST_N),
    .B(_215_),
    .C(_216_),
    .X(_217_)
  );
  sky130_fd_sc_hd__buf_1 _605_ (
    .A(_217_),
    .X(_081_)
  );
  sky130_fd_sc_hd__or4_2 _606_ (
    .A(\buffer3_exp1[1] ),
    .B(\buffer3_exp1[0] ),
    .C(\buffer3_exp1[3] ),
    .D(\buffer3_exp1[2] ),
    .X(_218_)
  );
  sky130_fd_sc_hd__nand2_2 _607_ (
    .A(\buffer3_man2[0] ),
    .B(_218_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o41a_2 _608_ (
    .A1(\buffer3_exp2[1] ),
    .A2(\buffer3_exp2[0] ),
    .A3(\buffer3_exp2[3] ),
    .A4(\buffer3_exp2[2] ),
    .B1(\buffer3_man1[0] ),
    .X(_220_)
  );
  sky130_fd_sc_hd__nand2_2 _609_ (
    .A(\buffer3_man1[1] ),
    .B(\buffer3_man2[2] ),
    .Y(_221_)
  );
  sky130_fd_sc_hd__xnor2_2 _610_ (
    .A(_220_),
    .B(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nand2_2 _611_ (
    .A(\buffer3_man2[1] ),
    .B(\buffer3_man1[2] ),
    .Y(_223_)
  );
  sky130_fd_sc_hd__xnor2_2 _612_ (
    .A(_222_),
    .B(_223_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__xnor2_2 _613_ (
    .A(_210_),
    .B(_224_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__xnor2_2 _614_ (
    .A(_219_),
    .B(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__xnor2_2 _615_ (
    .A(_212_),
    .B(_226_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nand2_2 _616_ (
    .A(_216_),
    .B(_227_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__o211a_2 _617_ (
    .A1(_216_),
    .A2(_226_),
    .B1(_228_),
    .C1(RST_N),
    .X(_082_)
  );
  sky130_fd_sc_hd__and3_2 _618_ (
    .A(\buffer3_man2[1] ),
    .B(\buffer3_man1[2] ),
    .C(_222_),
    .X(_229_)
  );
  sky130_fd_sc_hd__a31o_2 _619_ (
    .A1(\buffer3_man1[1] ),
    .A2(\buffer3_man2[2] ),
    .A3(_220_),
    .B1(_229_),
    .X(_230_)
  );
  sky130_fd_sc_hd__nand2_2 _620_ (
    .A(\buffer3_man2[1] ),
    .B(_218_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__or4_2 _621_ (
    .A(\buffer3_exp2[1] ),
    .B(\buffer3_exp2[0] ),
    .C(\buffer3_exp2[3] ),
    .D(\buffer3_exp2[2] ),
    .X(_232_)
  );
  sky130_fd_sc_hd__nand2_2 _622_ (
    .A(\buffer3_man2[2] ),
    .B(\buffer3_man1[2] ),
    .Y(_233_)
  );
  sky130_fd_sc_hd__a21bo_2 _623_ (
    .A1(\buffer3_man1[1] ),
    .A2(_232_),
    .B1_N(_233_),
    .X(_234_)
  );
  sky130_fd_sc_hd__inv_2 _624_ (
    .A(\buffer3_man1[1] ),
    .Y(_235_)
  );
  sky130_fd_sc_hd__or3b_2 _625_ (
    .A(_235_),
    .B(_233_),
    .C_N(_232_),
    .X(_236_)
  );
  sky130_fd_sc_hd__and2_2 _626_ (
    .A(_234_),
    .B(_236_),
    .X(_237_)
  );
  sky130_fd_sc_hd__xor2_2 _627_ (
    .A(_231_),
    .B(_237_),
    .X(_238_)
  );
  sky130_fd_sc_hd__xor2_2 _628_ (
    .A(_230_),
    .B(_238_),
    .X(_239_)
  );
  sky130_fd_sc_hd__nand2_2 _629_ (
    .A(_210_),
    .B(_224_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__o21a_2 _630_ (
    .A1(_219_),
    .A2(_225_),
    .B1(_240_),
    .X(_241_)
  );
  sky130_fd_sc_hd__xnor2_2 _631_ (
    .A(_239_),
    .B(_241_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__a21o_2 _632_ (
    .A1(_212_),
    .A2(_216_),
    .B1(_226_),
    .X(_243_)
  );
  sky130_fd_sc_hd__o21ai_2 _633_ (
    .A1(_242_),
    .A2(_243_),
    .B1(RST_N),
    .Y(_244_)
  );
  sky130_fd_sc_hd__a21oi_2 _634_ (
    .A1(_242_),
    .A2(_243_),
    .B1(_244_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__or2_2 _635_ (
    .A(_239_),
    .B(_241_),
    .X(_245_)
  );
  sky130_fd_sc_hd__o21a_2 _636_ (
    .A1(_242_),
    .A2(_243_),
    .B1(_245_),
    .X(_246_)
  );
  sky130_fd_sc_hd__or2b_2 _637_ (
    .A(_238_),
    .B_N(_230_),
    .X(_247_)
  );
  sky130_fd_sc_hd__or2b_2 _638_ (
    .A(_231_),
    .B_N(_237_),
    .X(_248_)
  );
  sky130_fd_sc_hd__nand2_2 _639_ (
    .A(\buffer3_man1[2] ),
    .B(_232_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__nand2_2 _640_ (
    .A(\buffer3_man2[2] ),
    .B(_218_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__xnor2_2 _641_ (
    .A(_249_),
    .B(_250_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__a21oi_2 _642_ (
    .A1(_236_),
    .A2(_248_),
    .B1(_251_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__and3_2 _643_ (
    .A(_236_),
    .B(_248_),
    .C(_251_),
    .X(_253_)
  );
  sky130_fd_sc_hd__or2_2 _644_ (
    .A(_252_),
    .B(_253_),
    .X(_254_)
  );
  sky130_fd_sc_hd__xnor2_2 _645_ (
    .A(_247_),
    .B(_254_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__a21oi_2 _646_ (
    .A1(_246_),
    .A2(_255_),
    .B1(_200_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__o21a_2 _647_ (
    .A1(_246_),
    .A2(_255_),
    .B1(_256_),
    .X(_084_)
  );
  sky130_fd_sc_hd__a31o_2 _648_ (
    .A1(_247_),
    .A2(_245_),
    .A3(_243_),
    .B1(_254_),
    .X(_257_)
  );
  sky130_fd_sc_hd__and3_2 _649_ (
    .A(_218_),
    .B(_232_),
    .C(_233_),
    .X(_258_)
  );
  sky130_fd_sc_hd__and2_2 _650_ (
    .A(_252_),
    .B(_258_),
    .X(_259_)
  );
  sky130_fd_sc_hd__nor2_2 _651_ (
    .A(_252_),
    .B(_258_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__or2_2 _652_ (
    .A(_259_),
    .B(_260_),
    .X(_261_)
  );
  sky130_fd_sc_hd__and2b_2 _653_ (
    .A_N(_257_),
    .B(_258_),
    .X(_262_)
  );
  sky130_fd_sc_hd__a211oi_2 _654_ (
    .A1(_257_),
    .A2(_261_),
    .B1(_262_),
    .C1(_200_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor2_2 _655_ (
    .A(_249_),
    .B(_250_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__o31a_2 _656_ (
    .A1(_263_),
    .A2(_259_),
    .A3(_262_),
    .B1(RST_N),
    .X(_086_)
  );
  sky130_fd_sc_hd__nor2_2 _657_ (
    .A(\final_man[4] ),
    .B(\final_man[3] ),
    .Y(_264_)
  );
  sky130_fd_sc_hd__or2_2 _658_ (
    .A(\final_man[1] ),
    .B(\final_man[2] ),
    .X(_265_)
  );
  sky130_fd_sc_hd__a21o_2 _659_ (
    .A1(_264_),
    .A2(_265_),
    .B1(\final_man[5] ),
    .X(_266_)
  );
  sky130_fd_sc_hd__nand2_2 _660_ (
    .A(\buffer3_exp[1] ),
    .B(_266_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__inv_2 _661_ (
    .A(\final_man[2] ),
    .Y(_268_)
  );
  sky130_fd_sc_hd__or2b_2 _662_ (
    .A(\final_man[1] ),
    .B_N(\final_man[0] ),
    .X(_269_)
  );
  sky130_fd_sc_hd__a21oi_2 _663_ (
    .A1(_268_),
    .A2(_269_),
    .B1(\final_man[3] ),
    .Y(_270_)
  );
  sky130_fd_sc_hd__inv_2 _664_ (
    .A(\final_man[5] ),
    .Y(_271_)
  );
  sky130_fd_sc_hd__a211o_2 _665_ (
    .A1(_264_),
    .A2(_265_),
    .B1(\final_man[5] ),
    .C1(\buffer3_exp[1] ),
    .X(_272_)
  );
  sky130_fd_sc_hd__o2111ai_2 _666_ (
    .A1(\final_man[4] ),
    .A2(_270_),
    .B1(\buffer3_exp[0] ),
    .C1(_271_),
    .D1(_272_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__nand2_2 _667_ (
    .A(_271_),
    .B(_264_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__nor2_2 _668_ (
    .A(\buffer3_exp[2] ),
    .B(_274_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__a21o_2 _669_ (
    .A1(_267_),
    .A2(_273_),
    .B1(_275_),
    .X(_276_)
  );
  sky130_fd_sc_hd__and2_2 _670_ (
    .A(\buffer3_exp[2] ),
    .B(_274_),
    .X(_277_)
  );
  sky130_fd_sc_hd__nor2_2 _671_ (
    .A(\buffer3_exp[3] ),
    .B(_277_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__o21a_2 _672_ (
    .A1(\final_man[4] ),
    .A2(_270_),
    .B1(_271_),
    .X(_279_)
  );
  sky130_fd_sc_hd__a21bo_2 _673_ (
    .A1(_276_),
    .A2(_278_),
    .B1_N(_279_),
    .X(_280_)
  );
  sky130_fd_sc_hd__nand3b_2 _674_ (
    .A_N(\buffer3_exp[0] ),
    .B(_276_),
    .C(_278_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__and2_2 _675_ (
    .A(_280_),
    .B(_281_),
    .X(_282_)
  );
  sky130_fd_sc_hd__o21ba_2 _676_ (
    .A1(\final_man[7] ),
    .A2(_282_),
    .B1_N(\buffer3_exp[0] ),
    .X(_283_)
  );
  sky130_fd_sc_hd__a21oi_2 _677_ (
    .A1(_276_),
    .A2(_278_),
    .B1(\final_man[7] ),
    .Y(_284_)
  );
  sky130_fd_sc_hd__a31o_2 _678_ (
    .A1(\buffer3_exp[0] ),
    .A2(_279_),
    .A3(_284_),
    .B1(_132_),
    .X(_285_)
  );
  sky130_fd_sc_hd__o221a_2 _679_ (
    .A1(\normalized_exp[0] ),
    .A2(_130_),
    .B1(_283_),
    .B2(_285_),
    .C1(RST_N),
    .X(_087_)
  );
  sky130_fd_sc_hd__a211o_2 _680_ (
    .A1(_267_),
    .A2(_272_),
    .B1(_279_),
    .C1(\buffer3_exp[0] ),
    .X(_286_)
  );
  sky130_fd_sc_hd__o211ai_2 _681_ (
    .A1(\buffer3_exp[0] ),
    .A2(_279_),
    .B1(_272_),
    .C1(_267_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__and3_2 _682_ (
    .A(_284_),
    .B(_286_),
    .C(_287_),
    .X(_288_)
  );
  sky130_fd_sc_hd__nand2_2 _683_ (
    .A(\buffer3_exp[1] ),
    .B(\buffer3_exp[0] ),
    .Y(_289_)
  );
  sky130_fd_sc_hd__or2_2 _684_ (
    .A(\buffer3_exp[1] ),
    .B(\buffer3_exp[0] ),
    .X(_290_)
  );
  sky130_fd_sc_hd__a31o_2 _685_ (
    .A1(\final_man[7] ),
    .A2(_289_),
    .A3(_290_),
    .B1(_132_),
    .X(_291_)
  );
  sky130_fd_sc_hd__o221a_2 _686_ (
    .A1(\normalized_exp[1] ),
    .A2(_129_),
    .B1(_288_),
    .B2(_291_),
    .C1(RST_N),
    .X(_088_)
  );
  sky130_fd_sc_hd__and2_2 _687_ (
    .A(_267_),
    .B(_273_),
    .X(_292_)
  );
  sky130_fd_sc_hd__or2_2 _688_ (
    .A(_275_),
    .B(_277_),
    .X(_293_)
  );
  sky130_fd_sc_hd__and3_2 _689_ (
    .A(_292_),
    .B(_287_),
    .C(_293_),
    .X(_294_)
  );
  sky130_fd_sc_hd__a21o_2 _690_ (
    .A1(_292_),
    .A2(_287_),
    .B1(_293_),
    .X(_295_)
  );
  sky130_fd_sc_hd__and2b_2 _691_ (
    .A_N(_294_),
    .B(_295_),
    .X(_296_)
  );
  sky130_fd_sc_hd__and3_2 _692_ (
    .A(\buffer3_exp[2] ),
    .B(\buffer3_exp[1] ),
    .C(\buffer3_exp[0] ),
    .X(_297_)
  );
  sky130_fd_sc_hd__a21oi_2 _693_ (
    .A1(\buffer3_exp[1] ),
    .A2(\buffer3_exp[0] ),
    .B1(\buffer3_exp[2] ),
    .Y(_298_)
  );
  sky130_fd_sc_hd__nor2_2 _694_ (
    .A(_297_),
    .B(_298_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__buf_1 _695_ (
    .A(_131_),
    .X(_300_)
  );
  sky130_fd_sc_hd__a221o_2 _696_ (
    .A1(_284_),
    .A2(_296_),
    .B1(_299_),
    .B2(\final_man[7] ),
    .C1(_300_),
    .X(_301_)
  );
  sky130_fd_sc_hd__o211a_2 _697_ (
    .A1(\normalized_exp[2] ),
    .A2(_130_),
    .B1(_301_),
    .C1(RST_N),
    .X(_089_)
  );
  sky130_fd_sc_hd__inv_2 _698_ (
    .A(_277_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__and3_2 _699_ (
    .A(\buffer3_exp[3] ),
    .B(_302_),
    .C(_295_),
    .X(_303_)
  );
  sky130_fd_sc_hd__a21o_2 _700_ (
    .A1(_302_),
    .A2(_295_),
    .B1(\buffer3_exp[3] ),
    .X(_304_)
  );
  sky130_fd_sc_hd__and4bb_2 _701_ (
    .A_N(\final_man[6] ),
    .B_N(_303_),
    .C(_284_),
    .D(_304_),
    .X(_305_)
  );
  sky130_fd_sc_hd__nand2_2 _702_ (
    .A(\buffer3_exp[3] ),
    .B(_297_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__or2_2 _703_ (
    .A(\buffer3_exp[3] ),
    .B(_297_),
    .X(_307_)
  );
  sky130_fd_sc_hd__a32o_2 _704_ (
    .A1(\final_man[7] ),
    .A2(_306_),
    .A3(_307_),
    .B1(_300_),
    .B2(\normalized_exp[3] ),
    .X(_308_)
  );
  sky130_fd_sc_hd__o21a_2 _705_ (
    .A1(_305_),
    .A2(_308_),
    .B1(RST_N),
    .X(_090_)
  );
  sky130_fd_sc_hd__xnor2_2 _706_ (
    .A(buffer1_sign2),
    .B(buffer1_sign1),
    .Y(_309_)
  );
  sky130_fd_sc_hd__nor2_2 _707_ (
    .A(_200_),
    .B(_309_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__mux2_2 _708_ (
    .A0(\buffer1_bias$D_IN[0] ),
    .A1(send_data_input[0]),
    .S(EN_send),
    .X(_310_)
  );
  sky130_fd_sc_hd__and2_2 _709_ (
    .A(RST_N),
    .B(_310_),
    .X(_311_)
  );
  sky130_fd_sc_hd__buf_1 _710_ (
    .A(_311_),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux2_2 _711_ (
    .A0(\buffer1_bias$D_IN[1] ),
    .A1(send_data_input[1]),
    .S(EN_send),
    .X(_312_)
  );
  sky130_fd_sc_hd__and2_2 _712_ (
    .A(RST_N),
    .B(_312_),
    .X(_313_)
  );
  sky130_fd_sc_hd__buf_1 _713_ (
    .A(_313_),
    .X(_093_)
  );
  sky130_fd_sc_hd__mux2_2 _714_ (
    .A0(\buffer1_bias$D_IN[2] ),
    .A1(send_data_input[2]),
    .S(EN_send),
    .X(_314_)
  );
  sky130_fd_sc_hd__and2_2 _715_ (
    .A(RST_N),
    .B(_314_),
    .X(_315_)
  );
  sky130_fd_sc_hd__buf_1 _716_ (
    .A(_315_),
    .X(_094_)
  );
  sky130_fd_sc_hd__mux2_2 _717_ (
    .A0(\buffer1_bias$D_IN[3] ),
    .A1(send_data_input[3]),
    .S(EN_send),
    .X(_316_)
  );
  sky130_fd_sc_hd__and2_2 _718_ (
    .A(RST_N),
    .B(_316_),
    .X(_317_)
  );
  sky130_fd_sc_hd__buf_1 _719_ (
    .A(_317_),
    .X(_095_)
  );
  sky130_fd_sc_hd__mux2_2 _720_ (
    .A0(\buffer1_rmode$D_IN ),
    .A1(send_data_input[4]),
    .S(EN_send),
    .X(_318_)
  );
  sky130_fd_sc_hd__and2_2 _721_ (
    .A(RST_N),
    .B(_318_),
    .X(_319_)
  );
  sky130_fd_sc_hd__buf_1 _722_ (
    .A(_319_),
    .X(_096_)
  );
  sky130_fd_sc_hd__mux2_2 _723_ (
    .A0(\buffer1_man2$D_IN[0] ),
    .A1(send_data_input[5]),
    .S(EN_send),
    .X(_320_)
  );
  sky130_fd_sc_hd__and2_2 _724_ (
    .A(RST_N),
    .B(_320_),
    .X(_321_)
  );
  sky130_fd_sc_hd__buf_1 _725_ (
    .A(_321_),
    .X(_097_)
  );
  sky130_fd_sc_hd__mux2_2 _726_ (
    .A0(\buffer1_man2$D_IN[1] ),
    .A1(send_data_input[6]),
    .S(EN_send),
    .X(_322_)
  );
  sky130_fd_sc_hd__and2_2 _727_ (
    .A(RST_N),
    .B(_322_),
    .X(_323_)
  );
  sky130_fd_sc_hd__buf_1 _728_ (
    .A(_323_),
    .X(_098_)
  );
  sky130_fd_sc_hd__mux2_2 _729_ (
    .A0(\buffer1_man2$D_IN[2] ),
    .A1(send_data_input[7]),
    .S(EN_send),
    .X(_324_)
  );
  sky130_fd_sc_hd__and2_2 _730_ (
    .A(RST_N),
    .B(_324_),
    .X(_325_)
  );
  sky130_fd_sc_hd__buf_1 _731_ (
    .A(_325_),
    .X(_099_)
  );
  sky130_fd_sc_hd__mux2_2 _732_ (
    .A0(\buffer1_exp2$D_IN[0] ),
    .A1(send_data_input[8]),
    .S(EN_send),
    .X(_326_)
  );
  sky130_fd_sc_hd__and2_2 _733_ (
    .A(RST_N),
    .B(_326_),
    .X(_327_)
  );
  sky130_fd_sc_hd__buf_1 _734_ (
    .A(_327_),
    .X(_100_)
  );
  sky130_fd_sc_hd__mux2_2 _735_ (
    .A0(\buffer1_exp2$D_IN[1] ),
    .A1(send_data_input[9]),
    .S(EN_send),
    .X(_328_)
  );
  sky130_fd_sc_hd__and2_2 _736_ (
    .A(RST_N),
    .B(_328_),
    .X(_329_)
  );
  sky130_fd_sc_hd__buf_1 _737_ (
    .A(_329_),
    .X(_101_)
  );
  sky130_fd_sc_hd__mux2_2 _738_ (
    .A0(\buffer1_exp2$D_IN[2] ),
    .A1(send_data_input[10]),
    .S(EN_send),
    .X(_330_)
  );
  sky130_fd_sc_hd__and2_2 _739_ (
    .A(RST_N),
    .B(_330_),
    .X(_331_)
  );
  sky130_fd_sc_hd__buf_1 _740_ (
    .A(_331_),
    .X(_102_)
  );
  sky130_fd_sc_hd__mux2_2 _741_ (
    .A0(\buffer1_exp2$D_IN[3] ),
    .A1(send_data_input[11]),
    .S(EN_send),
    .X(_332_)
  );
  sky130_fd_sc_hd__and2_2 _742_ (
    .A(RST_N),
    .B(_332_),
    .X(_333_)
  );
  sky130_fd_sc_hd__buf_1 _743_ (
    .A(_333_),
    .X(_103_)
  );
  sky130_fd_sc_hd__mux2_2 _744_ (
    .A0(\buffer1_sign2$D_IN ),
    .A1(send_data_input[12]),
    .S(EN_send),
    .X(_334_)
  );
  sky130_fd_sc_hd__and2_2 _745_ (
    .A(RST_N),
    .B(_334_),
    .X(_335_)
  );
  sky130_fd_sc_hd__buf_1 _746_ (
    .A(_335_),
    .X(_104_)
  );
  sky130_fd_sc_hd__mux2_2 _747_ (
    .A0(\buffer1_man1$D_IN[0] ),
    .A1(send_data_input[13]),
    .S(EN_send),
    .X(_336_)
  );
  sky130_fd_sc_hd__and2_2 _748_ (
    .A(RST_N),
    .B(_336_),
    .X(_337_)
  );
  sky130_fd_sc_hd__buf_1 _749_ (
    .A(_337_),
    .X(_105_)
  );
  sky130_fd_sc_hd__mux2_2 _750_ (
    .A0(\buffer1_man1$D_IN[1] ),
    .A1(send_data_input[14]),
    .S(EN_send),
    .X(_338_)
  );
  sky130_fd_sc_hd__and2_2 _751_ (
    .A(RST_N),
    .B(_338_),
    .X(_339_)
  );
  sky130_fd_sc_hd__buf_1 _752_ (
    .A(_339_),
    .X(_106_)
  );
  sky130_fd_sc_hd__mux2_2 _753_ (
    .A0(\buffer1_man1$D_IN[2] ),
    .A1(send_data_input[15]),
    .S(EN_send),
    .X(_340_)
  );
  sky130_fd_sc_hd__and2_2 _754_ (
    .A(RST_N),
    .B(_340_),
    .X(_341_)
  );
  sky130_fd_sc_hd__buf_1 _755_ (
    .A(_341_),
    .X(_107_)
  );
  sky130_fd_sc_hd__mux2_2 _756_ (
    .A0(\buffer1_exp1$D_IN[0] ),
    .A1(send_data_input[16]),
    .S(EN_send),
    .X(_342_)
  );
  sky130_fd_sc_hd__and2_2 _757_ (
    .A(RST_N),
    .B(_342_),
    .X(_343_)
  );
  sky130_fd_sc_hd__buf_1 _758_ (
    .A(_343_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2_2 _759_ (
    .A0(\buffer1_exp1$D_IN[1] ),
    .A1(send_data_input[17]),
    .S(EN_send),
    .X(_344_)
  );
  sky130_fd_sc_hd__and2_2 _760_ (
    .A(RST_N),
    .B(_344_),
    .X(_345_)
  );
  sky130_fd_sc_hd__buf_1 _761_ (
    .A(_345_),
    .X(_109_)
  );
  sky130_fd_sc_hd__mux2_2 _762_ (
    .A0(\buffer1_exp1$D_IN[2] ),
    .A1(send_data_input[18]),
    .S(EN_send),
    .X(_346_)
  );
  sky130_fd_sc_hd__and2_2 _763_ (
    .A(RST_N),
    .B(_346_),
    .X(_347_)
  );
  sky130_fd_sc_hd__buf_1 _764_ (
    .A(_347_),
    .X(_110_)
  );
  sky130_fd_sc_hd__mux2_2 _765_ (
    .A0(\buffer1_exp1$D_IN[3] ),
    .A1(send_data_input[19]),
    .S(EN_send),
    .X(_348_)
  );
  sky130_fd_sc_hd__and2_2 _766_ (
    .A(RST_N),
    .B(_348_),
    .X(_349_)
  );
  sky130_fd_sc_hd__buf_1 _767_ (
    .A(_349_),
    .X(_111_)
  );
  sky130_fd_sc_hd__mux2_2 _768_ (
    .A0(\buffer1_sign1$D_IN ),
    .A1(send_data_input[20]),
    .S(EN_send),
    .X(_350_)
  );
  sky130_fd_sc_hd__and2_2 _769_ (
    .A(RST_N),
    .B(_350_),
    .X(_351_)
  );
  sky130_fd_sc_hd__buf_1 _770_ (
    .A(_351_),
    .X(_112_)
  );
  sky130_fd_sc_hd__nor2_2 _771_ (
    .A(\normalized_man[2] ),
    .B(\normalized_man[3] ),
    .Y(_352_)
  );
  sky130_fd_sc_hd__and2_2 _772_ (
    .A(\normalized_man[2] ),
    .B(\normalized_man[3] ),
    .X(_353_)
  );
  sky130_fd_sc_hd__o21ai_2 _773_ (
    .A1(_352_),
    .A2(_353_),
    .B1(buffer5_rmode),
    .Y(_354_)
  );
  sky130_fd_sc_hd__o211a_2 _774_ (
    .A1(buffer5_rmode),
    .A2(\rounded_man[0] ),
    .B1(RST_N),
    .C1(_354_),
    .X(_113_)
  );
  sky130_fd_sc_hd__and3_2 _775_ (
    .A(\normalized_man[2] ),
    .B(\normalized_man[3] ),
    .C(\normalized_man[4] ),
    .X(_355_)
  );
  sky130_fd_sc_hd__nor2_2 _776_ (
    .A(\normalized_man[4] ),
    .B(_353_),
    .Y(_356_)
  );
  sky130_fd_sc_hd__o21ai_2 _777_ (
    .A1(_355_),
    .A2(_356_),
    .B1(buffer5_rmode),
    .Y(_357_)
  );
  sky130_fd_sc_hd__o211a_2 _778_ (
    .A1(buffer5_rmode),
    .A2(\rounded_man[1] ),
    .B1(RST_N),
    .C1(_357_),
    .X(_114_)
  );
  sky130_fd_sc_hd__xnor2_2 _779_ (
    .A(\normalized_man[5] ),
    .B(_355_),
    .Y(_358_)
  );
  sky130_fd_sc_hd__nand2_2 _780_ (
    .A(buffer5_rmode),
    .B(_358_),
    .Y(_359_)
  );
  sky130_fd_sc_hd__o211a_2 _781_ (
    .A1(\rounded_man[2] ),
    .A2(buffer5_rmode),
    .B1(RST_N),
    .C1(_359_),
    .X(_115_)
  );
  sky130_fd_sc_hd__nand2_2 _782_ (
    .A(_276_),
    .B(_278_),
    .Y(_360_)
  );
  sky130_fd_sc_hd__mux2_2 _783_ (
    .A0(_199_),
    .A1(_266_),
    .S(_360_),
    .X(_361_)
  );
  sky130_fd_sc_hd__buf_1 _784_ (
    .A(_361_),
    .X(_362_)
  );
  sky130_fd_sc_hd__inv_2 _785_ (
    .A(_362_),
    .Y(_363_)
  );
  sky130_fd_sc_hd__buf_1 _786_ (
    .A(_280_),
    .X(_364_)
  );
  sky130_fd_sc_hd__buf_1 _787_ (
    .A(_281_),
    .X(_365_)
  );
  sky130_fd_sc_hd__nand2_2 _788_ (
    .A(_364_),
    .B(_365_),
    .Y(_366_)
  );
  sky130_fd_sc_hd__and3_2 _789_ (
    .A(\final_man[1] ),
    .B(_364_),
    .C(_365_),
    .X(_367_)
  );
  sky130_fd_sc_hd__a21o_2 _790_ (
    .A1(\final_man[2] ),
    .A2(_366_),
    .B1(_367_),
    .X(_368_)
  );
  sky130_fd_sc_hd__a21o_2 _791_ (
    .A1(\final_man[0] ),
    .A2(_366_),
    .B1(_362_),
    .X(_369_)
  );
  sky130_fd_sc_hd__nor2_2 _792_ (
    .A(\final_man[6] ),
    .B(\final_man[7] ),
    .Y(_370_)
  );
  sky130_fd_sc_hd__o21bai_2 _793_ (
    .A1(\buffer3_exp[2] ),
    .A2(\buffer3_exp[3] ),
    .B1_N(_274_),
    .Y(_371_)
  );
  sky130_fd_sc_hd__o2111a_2 _794_ (
    .A1(_363_),
    .A2(_368_),
    .B1(_369_),
    .C1(_370_),
    .D1(_371_),
    .X(_372_)
  );
  sky130_fd_sc_hd__a22o_2 _795_ (
    .A1(\final_man[7] ),
    .A2(\final_man[3] ),
    .B1(_300_),
    .B2(\final_man[2] ),
    .X(_373_)
  );
  sky130_fd_sc_hd__o21a_2 _796_ (
    .A1(_372_),
    .A2(_373_),
    .B1(RST_N),
    .X(_116_)
  );
  sky130_fd_sc_hd__inv_2 _797_ (
    .A(\final_man[3] ),
    .Y(_374_)
  );
  sky130_fd_sc_hd__and3_2 _798_ (
    .A(_268_),
    .B(_364_),
    .C(_365_),
    .X(_375_)
  );
  sky130_fd_sc_hd__a21oi_2 _799_ (
    .A1(_374_),
    .A2(_366_),
    .B1(_375_),
    .Y(_376_)
  );
  sky130_fd_sc_hd__and3_2 _800_ (
    .A(\final_man[0] ),
    .B(_280_),
    .C(_281_),
    .X(_377_)
  );
  sky130_fd_sc_hd__a21boi_2 _801_ (
    .A1(_364_),
    .A2(_365_),
    .B1_N(\final_man[1] ),
    .Y(_378_)
  );
  sky130_fd_sc_hd__or3_2 _802_ (
    .A(_361_),
    .B(_377_),
    .C(_378_),
    .X(_379_)
  );
  sky130_fd_sc_hd__o211a_2 _803_ (
    .A1(_363_),
    .A2(_376_),
    .B1(_379_),
    .C1(_370_),
    .X(_380_)
  );
  sky130_fd_sc_hd__a22o_2 _804_ (
    .A1(\final_man[7] ),
    .A2(\final_man[4] ),
    .B1(\final_man[3] ),
    .B2(_300_),
    .X(_381_)
  );
  sky130_fd_sc_hd__o21a_2 _805_ (
    .A1(_380_),
    .A2(_381_),
    .B1(RST_N),
    .X(_117_)
  );
  sky130_fd_sc_hd__a31o_2 _806_ (
    .A1(\final_man[0] ),
    .A2(_366_),
    .A3(_362_),
    .B1(_371_),
    .X(_382_)
  );
  sky130_fd_sc_hd__a211o_2 _807_ (
    .A1(\final_man[2] ),
    .A2(_366_),
    .B1(_362_),
    .C1(_367_),
    .X(_383_)
  );
  sky130_fd_sc_hd__and3_2 _808_ (
    .A(_374_),
    .B(_364_),
    .C(_365_),
    .X(_384_)
  );
  sky130_fd_sc_hd__a21oi_2 _809_ (
    .A1(_364_),
    .A2(_365_),
    .B1(\final_man[4] ),
    .Y(_385_)
  );
  sky130_fd_sc_hd__o211ai_2 _810_ (
    .A1(_384_),
    .A2(_385_),
    .B1(_362_),
    .C1(_371_),
    .Y(_386_)
  );
  sky130_fd_sc_hd__and4_2 _811_ (
    .A(_370_),
    .B(_382_),
    .C(_383_),
    .D(_386_),
    .X(_387_)
  );
  sky130_fd_sc_hd__a22o_2 _812_ (
    .A1(\final_man[7] ),
    .A2(\final_man[5] ),
    .B1(\final_man[4] ),
    .B2(_300_),
    .X(_388_)
  );
  sky130_fd_sc_hd__o21a_2 _813_ (
    .A1(_387_),
    .A2(_388_),
    .B1(RST_N),
    .X(_118_)
  );
  sky130_fd_sc_hd__nand2_2 _814_ (
    .A(\final_man[5] ),
    .B(_300_),
    .Y(_389_)
  );
  sky130_fd_sc_hd__inv_2 _815_ (
    .A(\final_man[4] ),
    .Y(_390_)
  );
  sky130_fd_sc_hd__mux2_2 _816_ (
    .A0(_271_),
    .A1(_390_),
    .S(_282_),
    .X(_391_)
  );
  sky130_fd_sc_hd__a211o_2 _817_ (
    .A1(_374_),
    .A2(_366_),
    .B1(_362_),
    .C1(_375_),
    .X(_392_)
  );
  sky130_fd_sc_hd__o31ai_2 _818_ (
    .A1(_371_),
    .A2(_377_),
    .A3(_378_),
    .B1(_370_),
    .Y(_393_)
  );
  sky130_fd_sc_hd__a31o_2 _819_ (
    .A1(_371_),
    .A2(_391_),
    .A3(_392_),
    .B1(_393_),
    .X(_394_)
  );
  sky130_fd_sc_hd__a21oi_2 _820_ (
    .A1(_389_),
    .A2(_394_),
    .B1(_200_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__and2_2 _821_ (
    .A(RST_N),
    .B(final_sign),
    .X(_395_)
  );
  sky130_fd_sc_hd__buf_1 _822_ (
    .A(_395_),
    .X(_120_)
  );
  sky130_fd_sc_hd__xnor2_2 _823_ (
    .A(\buffer2_bias[0] ),
    .B(\buffer2_exp1[0] ),
    .Y(_396_)
  );
  sky130_fd_sc_hd__xnor2_2 _824_ (
    .A(\buffer2_exp2[0] ),
    .B(_396_),
    .Y(_397_)
  );
  sky130_fd_sc_hd__nor2_2 _825_ (
    .A(\buffer2_exp2[3] ),
    .B(\buffer2_exp1[3] ),
    .Y(_398_)
  );
  sky130_fd_sc_hd__and2_2 _826_ (
    .A(\buffer2_exp2[3] ),
    .B(\buffer2_exp1[3] ),
    .X(_399_)
  );
  sky130_fd_sc_hd__o21ba_2 _827_ (
    .A1(\buffer2_bias[3] ),
    .A2(_398_),
    .B1_N(_399_),
    .X(_400_)
  );
  sky130_fd_sc_hd__nor2_2 _828_ (
    .A(_399_),
    .B(_398_),
    .Y(_401_)
  );
  sky130_fd_sc_hd__xnor2_2 _829_ (
    .A(\buffer2_bias[3] ),
    .B(_401_),
    .Y(_402_)
  );
  sky130_fd_sc_hd__nand2_2 _830_ (
    .A(\buffer2_exp2[2] ),
    .B(\buffer2_exp1[2] ),
    .Y(_403_)
  );
  sky130_fd_sc_hd__or2_2 _831_ (
    .A(\buffer2_exp2[2] ),
    .B(\buffer2_exp1[2] ),
    .X(_404_)
  );
  sky130_fd_sc_hd__nand2_2 _832_ (
    .A(_403_),
    .B(_404_),
    .Y(_405_)
  );
  sky130_fd_sc_hd__o21ai_2 _833_ (
    .A1(\buffer2_bias[2] ),
    .A2(_405_),
    .B1(_403_),
    .Y(_406_)
  );
  sky130_fd_sc_hd__and2_2 _834_ (
    .A(_402_),
    .B(_406_),
    .X(_407_)
  );
  sky130_fd_sc_hd__nor2_2 _835_ (
    .A(_402_),
    .B(_406_),
    .Y(_408_)
  );
  sky130_fd_sc_hd__nor2_2 _836_ (
    .A(_407_),
    .B(_408_),
    .Y(_409_)
  );
  sky130_fd_sc_hd__xor2_2 _837_ (
    .A(\buffer2_bias[2] ),
    .B(_405_),
    .X(_410_)
  );
  sky130_fd_sc_hd__inv_2 _838_ (
    .A(\buffer2_bias[1] ),
    .Y(_411_)
  );
  sky130_fd_sc_hd__xor2_2 _839_ (
    .A(\buffer2_exp2[1] ),
    .B(\buffer2_exp1[1] ),
    .X(_412_)
  );
  sky130_fd_sc_hd__and2_2 _840_ (
    .A(\buffer2_exp2[1] ),
    .B(\buffer2_exp1[1] ),
    .X(_413_)
  );
  sky130_fd_sc_hd__a21o_2 _841_ (
    .A1(_411_),
    .A2(_412_),
    .B1(_413_),
    .X(_414_)
  );
  sky130_fd_sc_hd__or2b_2 _842_ (
    .A(\buffer2_exp1[0] ),
    .B_N(\buffer2_bias[0] ),
    .X(_415_)
  );
  sky130_fd_sc_hd__xnor2_2 _843_ (
    .A(\buffer2_bias[1] ),
    .B(_412_),
    .Y(_416_)
  );
  sky130_fd_sc_hd__and2_2 _844_ (
    .A(_415_),
    .B(_416_),
    .X(_417_)
  );
  sky130_fd_sc_hd__or2b_2 _845_ (
    .A(_396_),
    .B_N(\buffer2_exp2[0] ),
    .X(_418_)
  );
  sky130_fd_sc_hd__xnor2_2 _846_ (
    .A(_415_),
    .B(_416_),
    .Y(_419_)
  );
  sky130_fd_sc_hd__nor2_2 _847_ (
    .A(_418_),
    .B(_419_),
    .Y(_420_)
  );
  sky130_fd_sc_hd__xor2_2 _848_ (
    .A(_410_),
    .B(_414_),
    .X(_421_)
  );
  sky130_fd_sc_hd__o21ai_2 _849_ (
    .A1(_417_),
    .A2(_420_),
    .B1(_421_),
    .Y(_422_)
  );
  sky130_fd_sc_hd__a21bo_2 _850_ (
    .A1(_410_),
    .A2(_414_),
    .B1_N(_422_),
    .X(_423_)
  );
  sky130_fd_sc_hd__a21oi_2 _851_ (
    .A1(_409_),
    .A2(_423_),
    .B1(_407_),
    .Y(_424_)
  );
  sky130_fd_sc_hd__xnor2_2 _852_ (
    .A(_400_),
    .B(_424_),
    .Y(_425_)
  );
  sky130_fd_sc_hd__o21a_2 _853_ (
    .A1(_397_),
    .A2(_425_),
    .B1(RST_N),
    .X(_121_)
  );
  sky130_fd_sc_hd__and2_2 _854_ (
    .A(_418_),
    .B(_419_),
    .X(_426_)
  );
  sky130_fd_sc_hd__nor2_2 _855_ (
    .A(_420_),
    .B(_426_),
    .Y(_427_)
  );
  sky130_fd_sc_hd__o21a_2 _856_ (
    .A1(_425_),
    .A2(_427_),
    .B1(RST_N),
    .X(_122_)
  );
  sky130_fd_sc_hd__or3_2 _857_ (
    .A(_417_),
    .B(_420_),
    .C(_421_),
    .X(_428_)
  );
  sky130_fd_sc_hd__and2_2 _858_ (
    .A(_422_),
    .B(_428_),
    .X(_429_)
  );
  sky130_fd_sc_hd__o21a_2 _859_ (
    .A1(_425_),
    .A2(_429_),
    .B1(RST_N),
    .X(_123_)
  );
  sky130_fd_sc_hd__xor2_2 _860_ (
    .A(_409_),
    .B(_423_),
    .X(_430_)
  );
  sky130_fd_sc_hd__o21a_2 _861_ (
    .A1(_425_),
    .A2(_430_),
    .B1(RST_N),
    .X(_124_)
  );
  sky130_fd_sc_hd__and2_2 _862_ (
    .A(RST_N),
    .B(\stage1_output[7] ),
    .X(_431_)
  );
  sky130_fd_sc_hd__buf_1 _863_ (
    .A(_431_),
    .X(_125_)
  );
  sky130_fd_sc_hd__dfxtp_2 _864_ (
    .CLK(CLK),
    .D(_000_),
    .Q(receive[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _865_ (
    .CLK(CLK),
    .D(_001_),
    .Q(receive[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _866_ (
    .CLK(CLK),
    .D(_002_),
    .Q(receive[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _867_ (
    .CLK(CLK),
    .D(_003_),
    .Q(receive[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _868_ (
    .CLK(CLK),
    .D(_004_),
    .Q(receive[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _869_ (
    .CLK(CLK),
    .D(_005_),
    .Q(receive[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _870_ (
    .CLK(CLK),
    .D(_006_),
    .Q(receive[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _871_ (
    .CLK(CLK),
    .D(_007_),
    .Q(receive[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _872_ (
    .CLK(CLK),
    .D(_008_),
    .Q(\stage4_output[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _873_ (
    .CLK(CLK),
    .D(_009_),
    .Q(\stage4_output[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _874_ (
    .CLK(CLK),
    .D(_010_),
    .Q(\stage4_output[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _875_ (
    .CLK(CLK),
    .D(_011_),
    .Q(\stage4_output[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _876_ (
    .CLK(CLK),
    .D(_012_),
    .Q(\stage4_output[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _877_ (
    .CLK(CLK),
    .D(_013_),
    .Q(\buffer3_exp[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _878_ (
    .CLK(CLK),
    .D(_014_),
    .Q(\stage3_output[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _879_ (
    .CLK(CLK),
    .D(_015_),
    .Q(\buffer1_bias[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _880_ (
    .CLK(CLK),
    .D(_016_),
    .Q(\buffer1_bias[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _881_ (
    .CLK(CLK),
    .D(_017_),
    .Q(\buffer1_bias[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _882_ (
    .CLK(CLK),
    .D(_018_),
    .Q(\buffer1_bias[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _883_ (
    .CLK(CLK),
    .D(_019_),
    .Q(\buffer1_exp1[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _884_ (
    .CLK(CLK),
    .D(_020_),
    .Q(\buffer1_exp1[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _885_ (
    .CLK(CLK),
    .D(_021_),
    .Q(\buffer1_exp1[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _886_ (
    .CLK(CLK),
    .D(_022_),
    .Q(\buffer1_exp1[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _887_ (
    .CLK(CLK),
    .D(_023_),
    .Q(\buffer1_exp2[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _888_ (
    .CLK(CLK),
    .D(_024_),
    .Q(\buffer1_exp2[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _889_ (
    .CLK(CLK),
    .D(_025_),
    .Q(\buffer1_exp2[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _890_ (
    .CLK(CLK),
    .D(_026_),
    .Q(\buffer1_exp2[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _891_ (
    .CLK(CLK),
    .D(_027_),
    .Q(\buffer1_man1[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _892_ (
    .CLK(CLK),
    .D(_028_),
    .Q(\buffer1_man1[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _893_ (
    .CLK(CLK),
    .D(_029_),
    .Q(\buffer1_man1[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _894_ (
    .CLK(CLK),
    .D(_030_),
    .Q(\buffer1_man2[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _895_ (
    .CLK(CLK),
    .D(_031_),
    .Q(\buffer1_man2[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _896_ (
    .CLK(CLK),
    .D(_032_),
    .Q(\buffer1_man2[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _897_ (
    .CLK(CLK),
    .D(_033_),
    .Q(buffer1_rmode)
  );
  sky130_fd_sc_hd__dfxtp_2 _898_ (
    .CLK(CLK),
    .D(_034_),
    .Q(buffer1_sign1)
  );
  sky130_fd_sc_hd__dfxtp_2 _899_ (
    .CLK(CLK),
    .D(_035_),
    .Q(buffer1_sign2)
  );
  sky130_fd_sc_hd__dfxtp_2 _900_ (
    .CLK(CLK),
    .D(_036_),
    .Q(\buffer2_bias[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _901_ (
    .CLK(CLK),
    .D(_037_),
    .Q(\buffer2_bias[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _902_ (
    .CLK(CLK),
    .D(_038_),
    .Q(\buffer2_bias[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _903_ (
    .CLK(CLK),
    .D(_039_),
    .Q(\buffer2_bias[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _904_ (
    .CLK(CLK),
    .D(_040_),
    .Q(\buffer2_exp1[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _905_ (
    .CLK(CLK),
    .D(_041_),
    .Q(\buffer2_exp1[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _906_ (
    .CLK(CLK),
    .D(_042_),
    .Q(\buffer2_exp1[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _907_ (
    .CLK(CLK),
    .D(_043_),
    .Q(\buffer2_exp1[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _908_ (
    .CLK(CLK),
    .D(_044_),
    .Q(\buffer2_exp2[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _909_ (
    .CLK(CLK),
    .D(_045_),
    .Q(\buffer2_exp2[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _910_ (
    .CLK(CLK),
    .D(_046_),
    .Q(\buffer2_exp2[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _911_ (
    .CLK(CLK),
    .D(_047_),
    .Q(\buffer2_exp2[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _912_ (
    .CLK(CLK),
    .D(_048_),
    .Q(\buffer2_man1[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _913_ (
    .CLK(CLK),
    .D(_049_),
    .Q(\buffer2_man1[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _914_ (
    .CLK(CLK),
    .D(_050_),
    .Q(\buffer2_man1[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _915_ (
    .CLK(CLK),
    .D(_051_),
    .Q(\buffer2_man2[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _916_ (
    .CLK(CLK),
    .D(_052_),
    .Q(\buffer2_man2[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _917_ (
    .CLK(CLK),
    .D(_053_),
    .Q(\buffer2_man2[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _918_ (
    .CLK(CLK),
    .D(_054_),
    .Q(buffer2_rmode)
  );
  sky130_fd_sc_hd__dfxtp_2 _919_ (
    .CLK(CLK),
    .D(_055_),
    .Q(\buffer3_exp[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _920_ (
    .CLK(CLK),
    .D(_056_),
    .Q(\buffer3_exp[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _921_ (
    .CLK(CLK),
    .D(_057_),
    .Q(\buffer3_exp[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _922_ (
    .CLK(CLK),
    .D(_058_),
    .Q(\buffer3_exp1[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _923_ (
    .CLK(CLK),
    .D(_059_),
    .Q(\buffer3_exp1[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _924_ (
    .CLK(CLK),
    .D(_060_),
    .Q(\buffer3_exp1[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _925_ (
    .CLK(CLK),
    .D(_061_),
    .Q(\buffer3_exp1[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _926_ (
    .CLK(CLK),
    .D(_062_),
    .Q(\buffer3_exp2[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _927_ (
    .CLK(CLK),
    .D(_063_),
    .Q(\buffer3_exp2[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _928_ (
    .CLK(CLK),
    .D(_064_),
    .Q(\buffer3_exp2[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _929_ (
    .CLK(CLK),
    .D(_065_),
    .Q(\buffer3_exp2[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _930_ (
    .CLK(CLK),
    .D(_066_),
    .Q(\buffer3_man1[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _931_ (
    .CLK(CLK),
    .D(_067_),
    .Q(\buffer3_man1[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _932_ (
    .CLK(CLK),
    .D(_068_),
    .Q(\buffer3_man1[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _933_ (
    .CLK(CLK),
    .D(_069_),
    .Q(\buffer3_man2[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _934_ (
    .CLK(CLK),
    .D(_070_),
    .Q(\buffer3_man2[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _935_ (
    .CLK(CLK),
    .D(_071_),
    .Q(\buffer3_man2[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _936_ (
    .CLK(CLK),
    .D(_072_),
    .Q(buffer3_rmode)
  );
  sky130_fd_sc_hd__dfxtp_2 _937_ (
    .CLK(CLK),
    .D(_073_),
    .Q(\buffer4_exp[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _938_ (
    .CLK(CLK),
    .D(_074_),
    .Q(\buffer4_exp[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _939_ (
    .CLK(CLK),
    .D(_075_),
    .Q(\buffer4_exp[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _940_ (
    .CLK(CLK),
    .D(_076_),
    .Q(\buffer4_exp[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _941_ (
    .CLK(CLK),
    .D(_077_),
    .Q(buffer4_rmode)
  );
  sky130_fd_sc_hd__dfxtp_2 _942_ (
    .CLK(CLK),
    .D(_078_),
    .Q(buffer5_rmode)
  );
  sky130_fd_sc_hd__dfxtp_2 _943_ (
    .CLK(CLK),
    .D(_079_),
    .Q(\final_man[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _944_ (
    .CLK(CLK),
    .D(_080_),
    .Q(\final_man[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _945_ (
    .CLK(CLK),
    .D(_081_),
    .Q(\final_man[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _946_ (
    .CLK(CLK),
    .D(_082_),
    .Q(\final_man[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _947_ (
    .CLK(CLK),
    .D(_083_),
    .Q(\final_man[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _948_ (
    .CLK(CLK),
    .D(_084_),
    .Q(\final_man[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _949_ (
    .CLK(CLK),
    .D(_085_),
    .Q(\final_man[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _950_ (
    .CLK(CLK),
    .D(_086_),
    .Q(\final_man[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _951_ (
    .CLK(CLK),
    .D(_087_),
    .Q(\normalized_exp[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _952_ (
    .CLK(CLK),
    .D(_088_),
    .Q(\normalized_exp[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _953_ (
    .CLK(CLK),
    .D(_089_),
    .Q(\normalized_exp[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _954_ (
    .CLK(CLK),
    .D(_090_),
    .Q(\normalized_exp[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _955_ (
    .CLK(CLK),
    .D(_091_),
    .Q(final_sign)
  );
  sky130_fd_sc_hd__dfxtp_2 _956_ (
    .CLK(CLK),
    .D(_092_),
    .Q(\buffer1_bias$D_IN[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _957_ (
    .CLK(CLK),
    .D(_093_),
    .Q(\buffer1_bias$D_IN[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _958_ (
    .CLK(CLK),
    .D(_094_),
    .Q(\buffer1_bias$D_IN[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _959_ (
    .CLK(CLK),
    .D(_095_),
    .Q(\buffer1_bias$D_IN[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _960_ (
    .CLK(CLK),
    .D(_096_),
    .Q(\buffer1_rmode$D_IN )
  );
  sky130_fd_sc_hd__dfxtp_2 _961_ (
    .CLK(CLK),
    .D(_097_),
    .Q(\buffer1_man2$D_IN[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _962_ (
    .CLK(CLK),
    .D(_098_),
    .Q(\buffer1_man2$D_IN[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _963_ (
    .CLK(CLK),
    .D(_099_),
    .Q(\buffer1_man2$D_IN[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _964_ (
    .CLK(CLK),
    .D(_100_),
    .Q(\buffer1_exp2$D_IN[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _965_ (
    .CLK(CLK),
    .D(_101_),
    .Q(\buffer1_exp2$D_IN[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _966_ (
    .CLK(CLK),
    .D(_102_),
    .Q(\buffer1_exp2$D_IN[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _967_ (
    .CLK(CLK),
    .D(_103_),
    .Q(\buffer1_exp2$D_IN[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _968_ (
    .CLK(CLK),
    .D(_104_),
    .Q(\buffer1_sign2$D_IN )
  );
  sky130_fd_sc_hd__dfxtp_2 _969_ (
    .CLK(CLK),
    .D(_105_),
    .Q(\buffer1_man1$D_IN[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _970_ (
    .CLK(CLK),
    .D(_106_),
    .Q(\buffer1_man1$D_IN[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _971_ (
    .CLK(CLK),
    .D(_107_),
    .Q(\buffer1_man1$D_IN[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _972_ (
    .CLK(CLK),
    .D(_108_),
    .Q(\buffer1_exp1$D_IN[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _973_ (
    .CLK(CLK),
    .D(_109_),
    .Q(\buffer1_exp1$D_IN[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _974_ (
    .CLK(CLK),
    .D(_110_),
    .Q(\buffer1_exp1$D_IN[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _975_ (
    .CLK(CLK),
    .D(_111_),
    .Q(\buffer1_exp1$D_IN[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _976_ (
    .CLK(CLK),
    .D(_112_),
    .Q(\buffer1_sign1$D_IN )
  );
  sky130_fd_sc_hd__dfxtp_2 _977_ (
    .CLK(CLK),
    .D(_113_),
    .Q(\rounded_man[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _978_ (
    .CLK(CLK),
    .D(_114_),
    .Q(\rounded_man[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _979_ (
    .CLK(CLK),
    .D(_115_),
    .Q(\rounded_man[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _980_ (
    .CLK(CLK),
    .D(_116_),
    .Q(\normalized_man[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _981_ (
    .CLK(CLK),
    .D(_117_),
    .Q(\normalized_man[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _982_ (
    .CLK(CLK),
    .D(_118_),
    .Q(\normalized_man[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _983_ (
    .CLK(CLK),
    .D(_119_),
    .Q(\normalized_man[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _984_ (
    .CLK(CLK),
    .D(_120_),
    .Q(\stage1_output[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _985_ (
    .CLK(CLK),
    .D(_121_),
    .Q(\buffer3_exp$D_IN[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _986_ (
    .CLK(CLK),
    .D(_122_),
    .Q(\buffer3_exp$D_IN[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _987_ (
    .CLK(CLK),
    .D(_123_),
    .Q(\buffer3_exp$D_IN[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _988_ (
    .CLK(CLK),
    .D(_124_),
    .Q(\buffer3_exp$D_IN[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _989_ (
    .CLK(CLK),
    .D(_125_),
    .Q(\stage2_output[7] )
  );
  sky130_fd_sc_hd__buf_2 _990_ (
    .A(1'b1),
    .X(RDY_receive)
  );
  sky130_fd_sc_hd__buf_2 _991_ (
    .A(1'b1),
    .X(RDY_send)
  );
endmodule
